CREATE OR REPLACE TEMPORARY VIEW claim_837i
AS SELECT
         Claim_ID
        ,Claim_Type
        ,Payer_ID
        ,Payer_Name
        ,Patient_ID_Qualifier
        ,Patient_ID
        ,Patient_State
        ,Patient_Zip_Code
        ,Payer_Responsibility
        ,Patient_Relationship_Code
        ,Patient_First_Name
        ,Patient_Last_Name
        ,Patient_Gender_Code
        ,CAST(Patient_Birthday AS DATE) AS Patient_DOB
        ,Billing_Provider_ID
        ,Billing_Provider_ID_Qualifer
        ,Billing_Provider_NPI
        ,Billing_Provider_Organization_Individual_Name
        ,Billing_Provider_Street_Address_1
        ,Billing_Provider_Street_Address_2
        ,Billing_Provider_City
        ,Billing_Provider_State
        ,Billing_Provider_Zip
        ,Referring_Provider_NPI
        ,Referring_Provider_ID_Qualifier
        ,Referring_Provider_Last_Name
        ,Referring_Provider_First_Name
        ,Referring_Provider_Middle_Name
        ,Rendering_Attending_Provider_NPI
        ,Rendering_Attending_Provider_ID_Qualifier
        ,Rendering_Attending_Provider_Individual_Last_Name
        ,Rendering_Attending_Provider_Individual_First_Name
        ,Rendering_Attending_Provider_Individual_Middle_Name
        ,Facility_Name_Service
        ,Facility_Street_Address_1
        ,Facility_Street_Address_2
        ,Facility_City
        ,Facility_State
        ,Facility_Zip
        ,Statement_From_Date_Qualifier
        ,Statement_From_Date
        ,Statement_To_Date
        ,CAST(Total_Charge AS DECIMAL(10,2)) AS Total_Charge
        ,Code_List_Qualifier
        ,DRG_Code
        ,Bill_Type
        ,Release_of_Medical_Records_Signature
        ,Assignment_of_Benefits_Signature
        ,Principle_ICD_Procedure_Code_Qualifier
        ,Principle_ICD_Procedure_Code
        ,Principle_Diagnosis_Code_Qualifier
        ,Principle_Diagnosis_Code
        ,Admitting_Diagnosis_Code_Qualifier
        ,Admitting_Diagnosis_Code
        ,Code_Qualifier_1
        ,Other_Diagnosis_Code_1
        ,Code_Qualifier_2
        ,Other_Diagnosis_Code_2
        ,Code_Qualifier_3
        ,Other_Diagnosis_Code_3
        ,Code_Qualifier_4
        ,Other_Diagnosis_Code_4
        ,Code_Qualifier_5
        ,Other_Diagnosis_Code_5
        ,Code_Qualifier_6
        ,Other_Diagnosis_Code_6
        ,Code_Qualifier_7
        ,Other_Diagnosis_Code_7
        ,Code_Qualifier_8
        ,Other_Diagnosis_Code_8
        ,Code_Qualifier_9
        ,Other_Diagnosis_Code_9
        ,Code_Qualifier_10
        ,Other_Diagnosis_Code_10
        ,Code_Qualifier_11
        ,Other_Diagnosis_Code_11
        ,Code_Qualifier_12
        ,Other_Diagnosis_Code_12
        ,Code_Qualifier_13
        ,Other_Diagnosis_Code_13
        ,Code_Qualifier_14
        ,Other_Diagnosis_Code_14
        ,Code_Qualifier_15
        ,Other_Diagnosis_Code_15
        ,Code_Qualifier_16
        ,Other_Diagnosis_Code_16
        ,Code_Qualifier_17
        ,Other_Diagnosis_Code_17
        ,Code_Qualifier_18
        ,Other_Diagnosis_Code_18
        ,Code_Qualifier_19
        ,Other_Diagnosis_Code_19
        ,Code_Qualifier_20
        ,Other_Diagnosis_Code_20
        ,Code_Qualifier_21
        ,Other_Diagnosis_Code_21
        ,Code_Qualifier_22
        ,Other_Diagnosis_Code_22
        ,Code_Qualifier_23
        ,Other_Diagnosis_Code_23
        ,Code_Qualifier_24
        ,Other_Diagnosis_Code_24
        ,ICD_Code_Qualifier_1
        ,Other_ICD_Procedure_Code_1
        ,Other_ICD_Procedure_Date_Qualifier_1
        ,Other_ICD_Procedure_Date_1
        ,ICD_Code_Qualifier_2
        ,Other_ICD_Procedure_Code_2
        ,Other_ICD_Procedure_Date_Qualifier_2
        ,Other_ICD_Procedure_Date_2
        ,ICD_Code_Qualifier_3
        ,Other_ICD_Procedure_Code_3
        ,Other_ICD_Procedure_Date_Qualifier_3
        ,Other_ICD_Procedure_Date_3
        ,ICD_Code_Qualifier_4
        ,Other_ICD_Procedure_Code_4
        ,Other_ICD_Procedure_Date_Qualifier_4
        ,Other_ICD_Procedure_Date_4
        ,ICD_Code_Qualifier_5
        ,Other_ICD_Procedure_Code_5
        ,Other_ICD_Procedure_Date_Qualifier_5
        ,Other_ICD_Procedure_Date_5
        ,ICD_Code_Qualifier_6
        ,Other_ICD_Procedure_Code_6
        ,Other_ICD_Procedure_Date_Qualifier_6
        ,Other_ICD_Procedure_Date_6
        ,ICD_Code_Qualifier_7
        ,Other_ICD_Procedure_Code_7
        ,Other_ICD_Procedure_Date_Qualifier_7
        ,Other_ICD_Procedure_Date_7
        ,ICD_Code_Qualifier_8
        ,Other_ICD_Procedure_Code_8
        ,Other_ICD_Procedure_Date_Qualifier_8
        ,Other_ICD_Procedure_Date_8
        ,ICD_Code_Qualifier_9
        ,Other_ICD_Procedure_Code_9
        ,Other_ICD_Procedure_Date_Qualifier_9
        ,Other_ICD_Procedure_Date_9
        ,ICD_Code_Qualifier_10
        ,Other_ICD_Procedure_Code_10
        ,Other_ICD_Procedure_Date_Qualifier_10
        ,Other_ICD_Procedure_Date_10
        ,ICD_Code_Qualifier_11
        ,Other_ICD_Procedure_Code_11
        ,Other_ICD_Procedure_Date_Qualifier_11
        ,Other_ICD_Procedure_Date_11
        ,ICD_Code_Qualifier_12
        ,Other_ICD_Procedure_Code_12
        ,Other_ICD_Procedure_Date_Qualifier_12
        ,Other_ICD_Procedure_Date_12
        ,ICD_Code_Qualifier_13
        ,Other_ICD_Procedure_Code_13
        ,Other_ICD_Procedure_Date_Qualifier_13
        ,Other_ICD_Procedure_Date_13
        ,ICD_Code_Qualifier_14
        ,Other_ICD_Procedure_Code_14
        ,Other_ICD_Procedure_Date_Qualifier_14
        ,Other_ICD_Procedure_Date_14
        ,ICD_Code_Qualifier_15
        ,Other_ICD_Procedure_Code_15
        ,Other_ICD_Procedure_Date_Qualifier_15
        ,Other_ICD_Procedure_Date_15
        ,ICD_Code_Qualifier_16
        ,Other_ICD_Procedure_Code_16
        ,Other_ICD_Procedure_Date_Qualifier_16
        ,Other_ICD_Procedure_Date_16
        ,ICD_Code_Qualifier_17
        ,Other_ICD_Procedure_Code_17
        ,Other_ICD_Procedure_Date_Qualifier_17
        ,Other_ICD_Procedure_Date_17
        ,ICD_Code_Qualifier_18
        ,Other_ICD_Procedure_Code_18
        ,Other_ICD_Procedure_Date_Qualifier_18
        ,Other_ICD_Procedure_Date_18
        ,ICD_Code_Qualifier_19
        ,Other_ICD_Procedure_Code_19
        ,Other_ICD_Procedure_Date_Qualifier_19
        ,Other_ICD_Procedure_Date_19
        ,ICD_Code_Qualifier_20
        ,Other_ICD_Procedure_Code_20
        ,Other_ICD_Procedure_Date_Qualifier_20
        ,Other_ICD_Procedure_Date_20
        ,ICD_Code_Qualifier_21
        ,Other_ICD_Procedure_Code_21
        ,Other_ICD_Procedure_Date_Qualifier_21
        ,Other_ICD_Procedure_Date_21
        ,ICD_Code_Qualifier_22
        ,Other_ICD_Procedure_Code_22
        ,Other_ICD_Procedure_Date_Qualifier_22
        ,Other_ICD_Procedure_Date_22
        ,ICD_Code_Qualifier_23
        ,Other_ICD_Procedure_Code_23
        ,Other_ICD_Procedure_Date_Qualifier_23
        ,Other_ICD_Procedure_Date_23
        ,ICD_Code_Qualifier_24
        ,Other_ICD_Procedure_Code_24
        ,Other_ICD_Procedure_Date_Qualifier_24
        ,Other_ICD_Procedure_Date_24
        ,Claim_Filing_Indicator_Code
        ,Accident_Related_Indicator
        ,Admission_Date_Qualifier
        ,Admission_Date_Format_Qualifier
        ,CAST(Admission_Date AS DATE) AS Admission_Date
        ,Admission_Type_Code
        ,Admission_Source_Code
        ,Patient_Status_Code
        ,Billing_Provider_Taxonomy
        ,Billing_Provider_ID_Qualifer
        ,Billing_Provider_ID_State_License
        ,Rendering_Attending_Provider_Taxonomy
        ,Rendering_Attending_Provider_ID_Qualifier
        ,Rendering_Attending_Provider_ID_State_License
        ,Service_Facility_ID_Qualifier
        ,Facility_NPI
        ,Service_Facility_ID_Qualifier
        ,Facility_State_License
        ,Client_ID
        ,Feed_ID
        ,Token_1
        ,Token_2
        ,Token_3
        ,Token_4
        ,Token_8
        ,TokenEncryptionKey
FROM
    raw_claim_837i
